[package]
name = "zipdrip_framework"
version = "1.0.0"
authors = []

[addresses]
zipdrip_framework = "0x6e57ae098ab06ecc491d688a255b64b61dd52dbb58d2cce46e7def6013ffc2cd"
zipdrip = "0x6e57ae098ab06ecc491d688a255b64b61dd52dbb58d2cce46e7def6013ffc2cd"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
